apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
  replicas: 1
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        imagePullPolicy: Never
        image: ft-wordpress
        env:
        - name: WORDPRESS_DB_HOST
          value: mysql-svc
        - name: WORDPRESS_DB_USER
          value: root
        - name: WORDPRESS_DB_PASSWORD
          value: yash
        ports:
        - containerPort: 5050
          name: wordpress
        livenessProbe:
            exec:
              command:
              - /bin/sh
              - -c
              - ps -o comm | grep 'telegraf' && ps -o comm | grep 'php'
            initialDelaySeconds: 30
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress
  annotations:
    metallb.universe.tf/allow-shared-ip: address-pool
spec:
  selector:
    app: wordpress
  ports:
    - port: 5050
      targetPort: 5050
      protocol: TCP
      name: wordpress
  type: LoadBalancer
  loadBalancerIP: 172.17.0.230
