apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        imagePullPolicy: Never
        image: ft-mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: yash
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-ps
          mountPath: /var/lib/mysql/
      volumes:
      - name: mysql-ps
        persistentVolumeClaim:
          claimName: mysql-pv-claim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: mysql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
  annotations:
    metallb.universe.tf/allow-shared-ip : address-pool
spec:
  selector:
    app: mysql
  ports:
    - port: 3306
      protocol: TCP
      targetPort: 3306
      name: mysql
  type: ClusterIP
