apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: ft-nginx
        imagePullPolicy: Never
        env:
        - name: SSH_USER
          valueFrom:
            secretKeyRef:
              name: ssh-secret
              key: username
        - name: SSH_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ssh-secret
              key: password
        ports:
        - containerPort: 80
          name: http
        - containerPort: 22
          name: ssh
        - containerPort: 443
          name: https
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  annotations:
   metallb.universe.tf/allow-shared-ip: address-pool
spec:
  selector:
    app: nginx
  ports:
    - name: ssh
      port: 22
      targetPort: 22
      protocol: TCP
    - name: https
      port: 443
      targetPort: 443
      protocol: TCP
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
  type: LoadBalancer
  loadBalancerIP: 172.17.0.230


---
apiVersion: v1
kind: Secret
metadata:
  name: ssh-secret
stringData:
  username: admin
  password: admin