apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
spec:
  selector:
    matchLabels:
      app: phpmyadmin
  replicas: 1
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
      - name: phpmyadmin
        imagePullPolicy: Never
        image: ft-phpmyadmin
        ports:
        - containerPort: 5000
          name: phpmyadmin
        livenessProbe:
            exec:
              command:
              - /bin/sh
              - -c
              - ps -o comm | grep 'telegraf' && ps -o comm | grep 'nginx' && ps -o comm | grep 'php-fpm7'
            initialDelaySeconds: 30
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
  annotations:
    metallb.universe.tf/allow-shared-ip: address-pool
spec:
  selector:
    app: phpmyadmin
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
      name: phpmyadmin
  type: LoadBalancer
  loadBalancerIP: 172.17.0.230

